export {
    ChatStatus,
    createChatSchema,
    sendMessageSchema,
    getChatsSchema,
    getChatByIdSchema,
    transferChatSchema,
    markMessageAsReadSchema,
    markChatMessagesAsReadSchema,
    closeChatSchema,
    type CreateChatInput,
    type SendMessageInput,
    type GetChatsInput,
    type GetChatByIdInput,
    type TransferChatInput,
    type MarkMessageAsReadInput,
    type MarkChatMessagesAsReadInput,
    type CloseChatInput,
} from '@avenir/shared';
